services:
  db:
    image: postgres:17
    container_name: messanger_db
    env_file:
      - .env-dev
    ports:
      - "5432:5432"

  messanger:
    image: messanger_app
    build:
      context: .
    container_name: messanger_app
    env_file:
      - .env-dev
    depends_on:
      - db
    ports:
      - 8080:8080
    command: ["/entrypoint.sh"]

