"""Update chats

Revision ID: 60e4f741bffa
Revises: bb5f929c2b9e
Create Date: 2024-12-21 23:20:11.269004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e4f741bffa'
down_revision: Union[str, None] = 'bb5f929c2b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('second_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'second_name')
    # ### end Alembic commands ###
