"""change chats

Revision ID: 925d0ac54a7a
Revises: 60e4f741bffa
Create Date: 2025-01-07 16:10:06.629853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925d0ac54a7a'
down_revision: Union[str, None] = '60e4f741bffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'second_name')
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('second_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
