"""Update chats and mess

Revision ID: bb5f929c2b9e
Revises: 17d2adedf0b2
Create Date: 2024-12-21 22:03:07.506827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5f929c2b9e'
down_revision: Union[str, None] = '17d2adedf0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('chats', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
